name: "jvm Lint"
description: "Lints jvm repository"
inputs:
  checkout-repo:
    required: false
    description: "Perform checkout as first step of action"
    default: "true"
  github-token:
    required: true
    description: "GitHub token that can checkout the repository. e.g. 'secrets.GITHUB_TOKEN'"
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      if: inputs.checkout-repo
      with:
        fetch-depth: 0
    - uses: open-turo/action-pre-commit@v1
    - if: hashFiles('script/lint') != ''
      shell: bash
      run: script/lint
